### PR TITLE
Added command (CTRL-E) that exports all entries as a CSV for the current task

### PR DESCRIPTION
**Pull request by weakphish**
There is one issue - due to project and task IDs being private, I cannot seem to find a way to export the associated project and task for entries, as the ID is is private and names are not logged to the SQL DB.

Any tips or reviews would be great as I am a newb to Go!

### CODE REVIEW

**Comment by nanohard** [comment]
Uhmm, so yeah, looks like I didn't do associations correctly or something, or maybe it's GORM's fault. Yeah, that's right, it's GORM's fault. That's my story and I'm sticking to it. You have to pull the Project first, see the first two lines here. 
Also, do us a favor and pull latest master to sort out the `go.mod` conflict.
And as this function is directly relating to a particular Task I think moving it to `models/task.go` and changing the name to something really cool and edgy like `ExportTaskCsv` will make all those Java kids super jealous of our amazing naming scheme. Trust me.

```golang
...
var p Project
DB.First(&p, CurrentTask.ProjectID)

// write contents of each entry to a row in the CSV (string-writeable data)
for _, record := range entries {
timeWorked := record.End.Sub(record.Start) // user %v to format this when printing

values := []string{record.Details, timeWorked.String(), p.Name, CurrentTask.Name}
...
```

**Comment by John123Allison** [comment]
Conflicts are amended, I will work on the other stuff ASAP. Thanks!

P.S. TOTALLY GORM's fault... lol

**Comment by John123Allison** [comment]
Test this locally before merging, I encountered a bug that I believe was previously existing (I pulled from upstream in a VM and had it happen) where SQL queries randomly return errors.

**Comment by nanohard** [comment]
> Test this locally before merging, I encountered a bug that I believe was previously existing (I pulled from upstream in a VM and had it happen) where SQL queries randomly return errors.

That happens if you leave debug on in models/db.go

**Comment by John123Allison** [comment]
My mistake. Should be ready now.

**Comment by nanohard** [comment]
Sweet. Thanks!

**Pull request merged**
